# Generated by Django 5.0.8 on 2024-08-14 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookTable',
        ),
    ]
